"""Engine tool implementations, keyed by registry id (packages/shared/src/tools.ts).

Each module has `HEAVY` (queue class, DESIGN.md §3.2) and `async def run(ctx: ToolContext)`.
"""

from types import ModuleType

from werkbank_engine.tools import (
    audio_compress,
    audio_convert,
    audio_transcribe,
    download_media,
    pdf_clean_metadata,
    pdf_compare,
    pdf_compress,
    pdf_crop,
    pdf_extract,
    pdf_flatten,
    pdf_from_images,
    pdf_info,
    pdf_layout,
    pdf_merge,
    pdf_ocr,
    pdf_page_numbers,
    pdf_pages,
    pdf_protect,
    pdf_redact,
    pdf_repair,
    pdf_rotate,
    pdf_sign,
    pdf_split,
    pdf_tables,
    pdf_to_images,
    pdf_to_text,
    pdf_unlock,
    pdf_watermark,
    video_compress,
    video_convert,
)

IMPLEMENTATIONS: dict[str, ModuleType] = {
    "audio.compress": audio_compress,
    "audio.convert": audio_convert,
    "audio.transcribe": audio_transcribe,
    "download.media": download_media,
    "pdf.clean-metadata": pdf_clean_metadata,
    "pdf.compare": pdf_compare,
    "pdf.compress": pdf_compress,
    "pdf.crop": pdf_crop,
    "pdf.extract": pdf_extract,
    "pdf.flatten": pdf_flatten,
    "pdf.from-images": pdf_from_images,
    "pdf.info": pdf_info,
    "pdf.layout": pdf_layout,
    "pdf.merge": pdf_merge,
    "pdf.ocr": pdf_ocr,
    "pdf.page-numbers": pdf_page_numbers,
    "pdf.pages": pdf_pages,
    "pdf.protect": pdf_protect,
    "pdf.redact": pdf_redact,
    "pdf.repair": pdf_repair,
    "pdf.rotate": pdf_rotate,
    "pdf.sign": pdf_sign,
    "pdf.split": pdf_split,
    "pdf.tables": pdf_tables,
    "pdf.to-images": pdf_to_images,
    "pdf.to-text": pdf_to_text,
    "pdf.unlock": pdf_unlock,
    "pdf.watermark": pdf_watermark,
    "video.compress": video_compress,
    "video.convert": video_convert,
}
